<?php

namespace app\modules\home\controllers;
use app\modules\home\controllers\OverController;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\ShopDB;
use app\models\TypeDB;

class IndexController extends OverController
{
//    public $layout = 'dzf.php'; //布局页面
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'maxLength' => 4, //生成验证码最大个数
                'minLength' => 4, //生成验证码最小个数
                'width' => 80, //验证码的宽度
                'height' => 40, //验证码的高度
            ],
        ];
    }

    public function actionIndex()
    {
        /*查询最新上架的八件商品*/
        $mod = new ShopDB();
        $rst = $mod::find()->limit(8)->orderBy('time desc')->all();
        /*将数据对象转化成字符串*/
        foreach ($rst as $k=>$v){
            $rst[$k] = $v->attributes;
        }
        $mod = new TypeDB();
        $type = $mod->getsel('1');
        $color = $mod->getsel('28');
        $yotu = $mod->getsel('2');
        $baoz = $mod->getsel('3');
        return $this->render('index',['rst'=>$rst,'type'=>$type,'color'=>$color,'yotu'=>$yotu,'baoz'=>$baoz]);
    }
    //登录
    public function actionLogin(){
        $this->layout = 'dzf';
        $model = new \app\models\Login();
        $requesr = \Yii::$app->request;
        if ($requesr->isPost && $model->load($requesr->post()) && $model->validate()){
            $User = new \app\models\UserDB();
            $username = $model['user'];
            $pwd = md5($model['password']);
            $m_pwd = $User::find()->select(['id','user','pwd'])->where('user=:user',[':user'=>$username])->one();
            if ( $m_pwd->attributes['pwd'] == $pwd ) {
                $session = \Yii::$app->session;
                $session->set('users' , $m_pwd->attributes);
                return $this->redirect('./index.php?r=home/index/index');
            }else{
                return $this->redirect(\yii\helpers\Url::to(['index']));
            }
        }
        return $this->render('login' , ['model'=>$model]);
    }
    //注册
    public function actionRegister(){
        $this->layout = 'dzf';
        $model = new \app\models\Register();
        $requesr = \Yii::$app->request;
        if ($requesr->isPost && $model->load($requesr->post()) && $model->validate()){
            $User = new \app\models\UserDB();
            $User->user = $model['user'];
            $User->pwd = md5($model['password']);
            $User->time = date('Y-m-d H:i:s');
            if ($User->save()){
                $this->redirect(\yii\helpers\Url::to(['login']));
            }else{
                $this->redirect(\yii\helpers\Url::to(['register']));
            }
        }
        return $this->render('register' , ['model'=>$model]);
    }
    //找回密码
    public function actionFind(){

    }
    //退出
    public function actionTuichu(){
        \Yii::$app->session->set('users',null);
        return $this->redirect('./index.php?r=home/index/index');
    }
    //商品详情
    public function actionShops(){
        $id = \Yii::$app->request->get('ids');
        $mod = new ShopDB();
        $rst = $mod::findOne($id);
        return $this->render('shops',['rst'=>$rst]);
    }
    //进行购买
    public function actionShoping(){
        $id = \Yii::$app->request->get('ids');
        return $this->render('shoping',['data'=>$id]);
    }
}
